# (C) 2026 GoodData Corporation
import json
import os
import unittest
from unittest.mock import MagicMock

from gooddata_platform2cloud.metrics.maql.maql_builder import MaqlBuilder


def get_relative_path_to_current_folder():
    return os.path.dirname(os.path.realpath(__file__))


def get_files_with_prefix(folder_path, prefix):
    return [
        f
        for f in os.listdir(folder_path)
        if os.path.isfile(os.path.join(folder_path, f)) and f.startswith(prefix)
    ]


def load_json(file_path):
    with open(file_path, "r") as f:
        data = json.load(f)
    return data


def prepare_for_comparison(maql):
    maql = maql.replace(" ", "")
    maql = maql.replace(" ", "")
    maql = maql.replace("(", "")
    maql = maql.replace(")", "")
    maql = maql.replace(",", "")
    maql = maql.lower()
    return maql


class Maql_builder_platform_test(unittest.TestCase):
    """
    This is a test class for the MaqlBuilder class.
    """

    def test_maql_builder(self):
        """
        This is a test case for 'test_maql_builder' in the maql_builder_test class.
        It compares the maql generated by the MaqlBuilder class with the expression in the test data.
        """
        folder = f"{get_relative_path_to_current_folder()}/data/metrics"
        dataset_files = get_files_with_prefix(folder, "platform_metric")

        for dataset in dataset_files:
            json_data = load_json(f"{folder}/{dataset}")
            for test in json_data:
                content = test["metric"]["content"]

                # clean up the expression
                expression = content["expression"].replace("\n", " ")
                expression = " ".join(expression.split())

                mock_metric_context = MagicMock(name="MetricContext")
                builder = MaqlBuilder(mock_metric_context, content["tree"])
                maql = builder.get()

                maql = prepare_for_comparison(maql)
                expression = prepare_for_comparison(expression)

                self.assertEqual(maql, expression)


if __name__ == "__main__":
    unittest.main()
